version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_platform_frontend
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3000/api/v1
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    external: true 