version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_platform_frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '5173:5173'
    networks:
      - backendhaibanhh_app-network

networks:
  backendhaibanhh_app-network:
    external: true 